# This file was generated by GoReleaser. DO NOT EDIT.
cask "redis-tui" do
  name "redis-tui"
  desc "A powerful TUI for managing Redis databases"
  homepage "https://github.com/bearded-giant/redis-tui"
  version "1.0.33"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redis-tui"

  on_macos do
    on_intel do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "50437d69be15ad2068f901f33b226274d2fc2cf5475708ad7f9f89c60e928437"
    end
    on_arm do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_arm64.tar.gz"
      sha256 "0927dcf0e6dd477cc1818fdd6543b7489a914953f922eaa408199b44d9329d09"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_x86_64.tar.gz"
      sha256 "32f4179ae791f6014e9ebcf7bc0ebbd39952620dcacc78058470328460fd06df"
    end
    on_arm do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_arm64.tar.gz"
      sha256 "d88e5b5626d8a8c834e5ee9fa4754ab40f76b89a7119e360aa2087f6a293e9b1"
    end
  end

  # No zap stanza required
end
