# This file was generated by GoReleaser. DO NOT EDIT.
cask "redis-tui" do
  name "redis-tui"
  desc "A powerful TUI for managing Redis databases"
  homepage "https://github.com/bearded-giant/redis-tui"
  version "1.0.34"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redis-tui"

  on_macos do
    on_intel do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "fddcb43e85a6d6c4baa23ed46f0bb02561b378511c9efc08f19222df331475bb"
    end
    on_arm do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_arm64.tar.gz"
      sha256 "02aaa34ea7e9d722bb3f22cbffe1b9c3dcec91cb62057e2bc52bfe774d230afd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_x86_64.tar.gz"
      sha256 "32d9d97318a22569ef226269f81fff328ff059321342179af807c1a2691722c9"
    end
    on_arm do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_arm64.tar.gz"
      sha256 "e30be1beee5afa273438da8ccc843921f4f768765b8fd9719244738751ad63e5"
    end
  end

  # No zap stanza required
end
