# This file was generated by GoReleaser. DO NOT EDIT.
cask "redis-tui" do
  name "redis-tui"
  desc "A powerful TUI for managing Redis databases"
  homepage "https://github.com/bearded-giant/redis-tui"
  version "1.0.35"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redis-tui"

  on_macos do
    on_intel do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b29b02e34d6317ee8b1eb1387e688eb1d44c359a5c2798c08796edc3ec5633c8"
    end
    on_arm do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_arm64.tar.gz"
      sha256 "d5fd3b7616d8ad36f3e3cd3cd21a1060a5e0856b37bd4a511b0be691873a5717"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_x86_64.tar.gz"
      sha256 "03c0f05ac2df6ab770564fb612daf0b9e3b3eb2b8f8a38e39a46767461e3169f"
    end
    on_arm do
      url "https://github.com/bearded-giant/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_arm64.tar.gz"
      sha256 "28843dba884e685ac5ee28d9f6c29a7d8e4de27bb71fbdcbeca54bb18f3c01a8"
    end
  end

  # No zap stanza required
end
